name = "vgallery-space"
compatibility_date = "2026-09-08"
workers_dev = true

routes = [
  { pattern = "vgallery.space/*", zone_name = "vgallery.space" },
  { pattern = "www.vgallery.space/*", zone_name = "vgallery.space" }
]

[assets]
directory = "."
